"""Initial migration -3

Revision ID: 318d3594ec3e
Revises: 79271458a973
Create Date: 2024-12-13 21:22:42.921020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '318d3594ec3e'
down_revision = '79271458a973'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('creator_admin_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('DEPOSIT', 'WITHDRAWAL', name='admintransactiontype'), nullable=False),
    sa.Column('amount_gigabytes', sa.Integer(), nullable=False),
    sa.Column('amount_rials', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('note', sa.String(length=256), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], ),
    sa.ForeignKeyConstraint(['creator_admin_id'], ['admins.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.alter_column('hosts', 'alpn',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.String(length=32),
               nullable=True,
               existing_server_default=sa.text("'none'"))
    op.alter_column('inbounds', 'protocol',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.Enum('VMess', 'VLESS', 'Trojan', 'Shadowsocks', 'Shadowsocks2022', 'Hysteria2', 'WireGuard', 'TUIC', 'ShadowTLS', name='proxytypes'),
               existing_nullable=True)
    op.alter_column('users', 'usage_duration',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'usage_duration',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('inbounds', 'protocol',
               existing_type=sa.Enum('VMess', 'VLESS', 'Trojan', 'Shadowsocks', 'Shadowsocks2022', 'Hysteria2', 'WireGuard', 'TUIC', 'ShadowTLS', name='proxytypes'),
               type_=sa.VARCHAR(length=11),
               existing_nullable=True)
    op.alter_column('hosts', 'alpn',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=11),
               nullable=False,
               existing_server_default=sa.text("'none'"))
    op.drop_table('admin_transactions')
    # ### end Alembic commands ###
