"""Initial migration --- xxxx

Revision ID: 6667fc25f451
Revises: 318d3594ec3e
Create Date: 2024-12-15 19:06:37.459375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6667fc25f451'
down_revision = '318d3594ec3e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('hosts', 'alpn',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.String(length=32),
               nullable=True,
               existing_server_default=sa.text("'none'"))
    op.alter_column('inbounds', 'protocol',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.Enum('VMess', 'VLESS', 'Trojan', 'Shadowsocks', 'Shadowsocks2022', 'Hysteria2', 'WireGuard', 'TUIC', 'ShadowTLS', name='proxytypes'),
               existing_nullable=True)
    op.alter_column('users', 'usage_duration',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'usage_duration',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('inbounds', 'protocol',
               existing_type=sa.Enum('VMess', 'VLESS', 'Trojan', 'Shadowsocks', 'Shadowsocks2022', 'Hysteria2', 'WireGuard', 'TUIC', 'ShadowTLS', name='proxytypes'),
               type_=sa.VARCHAR(length=11),
               existing_nullable=True)
    op.alter_column('hosts', 'alpn',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=11),
               nullable=False,
               existing_server_default=sa.text("'none'"))
    # ### end Alembic commands ###
