"""change col amount to floadt

Revision ID: 87f884a80591
Revises: 6667fc25f451
Create Date: 2024-12-16 10:02:06.203587

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '87f884a80591'
down_revision = '6667fc25f451'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('admin_transactions', 'amount_gigabytes',
               existing_type=mysql.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('admin_transactions', 'amount_rials',
               existing_type=mysql.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('admin_transactions', 'amount_rials',
               existing_type=sa.Float(),
               type_=mysql.INTEGER(),
               existing_nullable=False)
    op.alter_column('admin_transactions', 'amount_gigabytes',
               existing_type=sa.Float(),
               type_=mysql.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
