"""Initial migration -3

Revision ID: 318d3594ec3e
Revises: 79271458a973
Create Date: 2024-12-13 21:22:42.921020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '318d3594ec3e'
down_revision = '79271458a973'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('creator_admin_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('DEPOSIT', 'WITHDRAWAL', name='admintransactiontype'), nullable=False),
    sa.Column('amount_gigabytes', sa.Integer(), nullable=False),
    sa.Column('amount_rials', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('note', sa.String(length=256), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], ),
    sa.ForeignKeyConstraint(['creator_admin_id'], ['admins.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
