name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH
        run: |
          set -x
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p ${{ vars.SSH_PORT }} -H ${{ vars.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Kill all current dockers
        run: |
          ssh -p ${{ vars.SSH_PORT }} root@${{ vars.SERVER_IP }} 'bash ~/kill.sh'

      - name: Delete Existing PM2 Process
        run: |
          ssh -p ${{ vars.SSH_PORT }} root@${{ vars.SERVER_IP }} 'cd /var/lib/marzneshin && git pull && make dashboard-deps && make dashboard-build'

      - name: Move Extracted Files to Parent Directory
        run: |
          ssh -p ${{ vars.SSH_PORT }} root@${{ vars.SERVER_IP }} 'cd /var/lib/marzneshin && docker compose -f ./docker-compose.dev.custom.yml up -d'